version: "3.7"

services:
  dynamodb-setup:
    image: banst/awscli
    depends_on:
      - dynamodb
    environment:
      AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
      AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'
      REGION: 'eu-west-1'
    volumes:
      - ./scripts:/home/dynamodb-setup/scripts
    working_dir: /home/dynamodb-setup
    entrypoint: /bin/sh
    command: ./scripts/init-tables.sh
    #entrypoint: tail
    #command: -f ./scripts/init-tables.sh
